'use strict';

const fs = require('fs-extra');
const path = require('path');
const Mustache = require('mustache');
const ora = require('ora');
const logger = require('../lib/logger');
const { readProjectManifest } = require('../lib/project');

/** Directory where generated marketing assets are written. */
const MARKETING_DIR = 'marketing';

// ---------------------------------------------------------------------------
// Mustache templates
// ---------------------------------------------------------------------------

const README_TEMPLATE = `# {{name}}

> {{description}}

## ✨ Features

{{#features}}
- {{.}}
{{/features}}

## 📦 Installation

\`\`\`bash
npm install {{name}}
\`\`\`

## 🚀 Quick Start

\`\`\`bash
npx {{name}}
\`\`\`

## 🛠 Version

**{{version}}**{{#homepage}}

## 🔗 Links

- [Homepage]({{homepage}}){{/homepage}}

---

*Generated by [Imagia](https://github.com/hapitech/imagia) on {{generatedAt}}*
`;

const HTML_PREVIEW_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{name}} – Preview</title>
  <style>
    :root { --accent: #6366f1; }
    body { font-family: system-ui, sans-serif; margin: 0; background: #0f172a; color: #e2e8f0; }
    header { background: var(--accent); padding: 3rem 2rem; text-align: center; }
    header h1 { font-size: 3rem; margin: 0; color: #fff; }
    header p  { font-size: 1.25rem; color: #e0e7ff; margin-top: 0.5rem; }
    main { max-width: 860px; margin: 2rem auto; padding: 0 1.5rem; }
    .badge { display: inline-block; background: var(--accent); color: #fff;
             border-radius: 9999px; padding: 0.2rem 0.75rem; font-size: 0.85rem;
             margin-right: 0.4rem; }
    .features { list-style: none; padding: 0; display: grid;
                grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 1rem; }
    .features li { background: #1e293b; border-radius: 0.75rem; padding: 1rem 1.25rem; }
    .features li::before { content: "✨ "; }
    .install { background: #1e293b; border-radius: 0.75rem; padding: 1rem 1.25rem;
               font-family: monospace; margin-top: 1.5rem; }
    footer { text-align: center; padding: 2rem; color: #64748b; font-size: 0.85rem; }
  </style>
</head>
<body>
  <header>
    <h1>{{name}}</h1>
    <p>{{description}}</p>
    <span class="badge">v{{version}}</span>
    <span class="badge">{{license}}</span>
  </header>
  <main>
    <h2>✨ Features</h2>
    <ul class="features">
      {{#features}}
      <li>{{.}}</li>
      {{/features}}
    </ul>

    <h2>📦 Installation</h2>
    <div class="install">npm install {{name}}</div>
  </main>
  <footer>
    Generated by <a href="https://github.com/hapitech/imagia" style="color:var(--accent)">Imagia</a>
    on {{generatedAt}}
  </footer>
</body>
</html>
`;

const SOCIAL_TEMPLATE = `{{name}} – {{description}}

🚀 Version {{version}}
{{#features}}
✅ {{.}}
{{/features}}
{{#homepage}}
🔗 {{homepage}}
{{/homepage}}
#builtwithimagia #nodejs #opensource`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extract a list of features from a package.json.
 * Uses pkg.imagia.features if present, otherwise falls back to keywords.
 * @param {object} pkg
 * @returns {string[]}
 */
function extractFeatures(pkg) {
  if (pkg.imagia && Array.isArray(pkg.imagia.features) && pkg.imagia.features.length > 0) {
    return pkg.imagia.features;
  }
  if (Array.isArray(pkg.keywords) && pkg.keywords.length > 0) {
    return pkg.keywords.map((k) => k.charAt(0).toUpperCase() + k.slice(1));
  }
  return ['Fast and lightweight', 'Easy to use', 'Fully configurable'];
}

/**
 * Build the template context from the project manifest.
 * @param {object} pkg
 * @returns {object}
 */
function buildContext(pkg) {
  return {
    name: pkg.name || 'my-app',
    version: pkg.version || '1.0.0',
    description: pkg.description || 'An awesome application',
    license: pkg.license || 'ISC',
    homepage: pkg.homepage || '',
    features: extractFeatures(pkg),
    generatedAt: new Date().toUTCString(),
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate marketing collateral for the project.
 *
 * Outputs to <dir>/marketing/:
 *   - MARKETING_README.md   – polished markdown README
 *   - preview.html          – standalone HTML preview page
 *   - social.txt            – social-media–ready snippet
 *
 * @param {object} options
 * @param {string}  options.dir    - Project root directory (default: cwd)
 * @param {boolean} options.silent - Suppress spinner/log output
 * @returns {Promise<{ outDir: string, files: string[] }>}
 */
async function market({ dir = process.cwd(), silent = false } = {}) {
  logger.title('\n📣  Imagia – Marketing Collateral');

  const pkg = readProjectManifest(dir);
  const ctx = buildContext(pkg);

  const outDir = path.join(dir, MARKETING_DIR);
  await fs.ensureDir(outDir);

  const spinner = ora({ text: 'Generating marketing collateral…', isSilent: silent }).start();

  const files = [];

  // 1. Marketing README
  const readmePath = path.join(outDir, 'MARKETING_README.md');
  await fs.writeFile(readmePath, Mustache.render(README_TEMPLATE, ctx), 'utf8');
  files.push(readmePath);

  // 2. HTML preview
  const htmlPath = path.join(outDir, 'preview.html');
  await fs.writeFile(htmlPath, Mustache.render(HTML_PREVIEW_TEMPLATE, ctx), 'utf8');
  files.push(htmlPath);

  // 3. Social media snippet
  const socialPath = path.join(outDir, 'social.txt');
  await fs.writeFile(socialPath, Mustache.render(SOCIAL_TEMPLATE, ctx), 'utf8');
  files.push(socialPath);

  spinner.succeed('Marketing collateral generated.');

  files.forEach((f) => logger.success(`  ${path.relative(dir, f)}`));

  return { outDir, files };
}

module.exports = { market, extractFeatures, buildContext, MARKETING_DIR };
