import { Link } from 'react-router-dom';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-200 bg-white">
        <div className="mx-auto max-w-4xl px-6 py-4 flex items-center justify-between">
          <Link to="/" className="text-xl font-bold text-gray-900">Imagia</Link>
          <div className="flex gap-4 text-sm">
            <Link to="/privacy" className="text-gray-600 hover:text-gray-900">Privacy Policy</Link>
            <Link to="/sign-in" className="text-indigo-600 hover:text-indigo-700 font-medium">Sign In</Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: February 28, 2026</p>

        <div className="prose prose-gray max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using Imagia ("the Service"), operated at imagia.net, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed">
              Imagia is an AI-powered application builder that allows users to create, deploy, and manage web applications through a conversational interface. The Service includes code generation, image generation, marketing asset creation, deployment, and related features.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">3. Account Registration</h2>
            <p className="text-gray-700 leading-relaxed">
              To use the Service, you must create an account using a supported authentication provider (Google or GitHub). You are responsible for maintaining the security of your account and for all activities that occur under your account. You must provide accurate and complete information when creating your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">4. Acceptable Use</h2>
            <p className="text-gray-700 leading-relaxed">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mt-2">
              <li>Violate any applicable laws or regulations</li>
              <li>Generate malicious code, malware, or content designed to harm others</li>
              <li>Infringe upon the intellectual property rights of others</li>
              <li>Generate content that is illegal, harmful, threatening, abusive, or hateful</li>
              <li>Attempt to gain unauthorized access to the Service or other users' accounts</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Use the Service to spam, phish, or conduct fraudulent activities</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">5. Intellectual Property</h2>
            <h3 className="text-lg font-medium text-gray-800 mt-4 mb-2">Your Content</h3>
            <p className="text-gray-700 leading-relaxed">
              You retain ownership of the projects, code, and content you create using the Service. By using the Service, you grant us a limited license to store, process, and display your content as necessary to provide the Service.
            </p>
            <h3 className="text-lg font-medium text-gray-800 mt-4 mb-2">AI-Generated Content</h3>
            <p className="text-gray-700 leading-relaxed">
              Code, images, and other content generated by AI models through the Service are provided to you for your use. You are responsible for reviewing and ensuring that AI-generated content is suitable for your purposes and complies with applicable laws.
            </p>
            <h3 className="text-lg font-medium text-gray-800 mt-4 mb-2">Our Service</h3>
            <p className="text-gray-700 leading-relaxed">
              The Service, including its design, features, and underlying technology, is owned by Imagia and protected by intellectual property laws. These terms do not grant you any rights to our trademarks, logos, or branding.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">6. AI-Powered Features</h2>
            <p className="text-gray-700 leading-relaxed">
              The Service uses third-party AI models (including Fireworks AI, OpenAI, and Anthropic) to generate code, images, and content. AI-generated output may not always be accurate, complete, or suitable for production use. You are solely responsible for reviewing, testing, and validating any AI-generated output before using it in production environments.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">7. Deployment and Hosting</h2>
            <p className="text-gray-700 leading-relaxed">
              When you deploy applications through the Service, they are hosted on third-party infrastructure. We make reasonable efforts to maintain availability but do not guarantee uptime for deployed applications. You are responsible for the content and behavior of applications you deploy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">8. Fees and Payment</h2>
            <p className="text-gray-700 leading-relaxed">
              The Service may include free and paid tiers. We reserve the right to introduce, modify, or discontinue pricing at any time with reasonable notice. Usage of AI models and hosting resources may be subject to limits.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">9. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              To the maximum extent permitted by law, Imagia shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising out of or related to your use of the Service. The Service is provided "as is" and "as available" without warranties of any kind, either express or implied.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">10. Indemnification</h2>
            <p className="text-gray-700 leading-relaxed">
              You agree to indemnify and hold harmless Imagia from any claims, losses, damages, liabilities, and expenses (including legal fees) arising out of your use of the Service, your violation of these Terms, or your violation of any third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">11. Termination</h2>
            <p className="text-gray-700 leading-relaxed">
              We may suspend or terminate your access to the Service at any time for violation of these Terms or for any other reason at our discretion. You may delete your account at any time. Upon termination, your right to use the Service ceases immediately, though we may retain certain data as required by law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">12. Changes to Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify you of material changes by updating the "Last updated" date. Your continued use of the Service after changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">13. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Imagia operates, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">14. Contact Us</h2>
            <p className="text-gray-700 leading-relaxed">
              If you have questions about these Terms, please contact us at <a href="mailto:legal@imagia.net" className="text-indigo-600 hover:text-indigo-700">legal@imagia.net</a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-gray-200 bg-white mt-12">
        <div className="mx-auto max-w-4xl px-6 py-6 flex items-center justify-between text-sm text-gray-500">
          <span>&copy; {new Date().getFullYear()} Imagia. All rights reserved.</span>
          <div className="flex gap-4">
            <Link to="/privacy" className="hover:text-gray-700">Privacy Policy</Link>
            <Link to="/terms" className="hover:text-gray-700">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
